name: hierasynth
version: 0.1.0.0
synopsis: Library for building synthesizers with HieraSynth
description: Library for building synthesizers with HieraSynth
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >= 4.14 && < 5
  - grisette >= 0.12 && < 0.13
  - mtl >= 2.2.2 && < 2.4
  - unordered-containers >= 0.2.11 && < 0.3
  - QuickCheck >= 2.14.1 && < 2.16
  - quickcheck-with-counterexamples >= 1.2 && < 1.3
  - sbv >= 8.17 && < 12
  - hashable >= 1.3 && < 1.6
  - text >= 1.2.4.1 && < 2.2
  - prettyprinter >= 1.5 && < 1.8
  - ordered-containers >= 0.2.3 && < 0.3
  - deepseq
  - graphviz >= 2999.20.0.4 && < 3000
  - extra
  - template-haskell
  - stm
  - containers
  - async
  - time
  - psqueues
  - safe-exceptions
  - cereal
  - bytes
  - binary
  - hslogger
  - unix
  - bytestring
  - ansi-terminal
  - random >= 1.2 && < 1.3
  - Chart >= 1.9.3 && < 1.10
  - Chart-cairo >= 1.9.3 && < 1.10
  - megaparsec
  - parser-combinators
ghc-options:
  - -Wextra
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wno-x-partial
  - -Wno-unrecognised-warning-flags
library:
  source-dirs: src
executables:
  arith:
    source-dirs: arith
    main: Main.hs
    dependencies: hierasynth
  arith-sum:
    source-dirs: arith-sum
    main: Main.hs
    dependencies: hierasynth
  control:
    source-dirs: control
    main: Main.hs
    dependencies: hierasynth
tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - hierasynth
      - test-framework >= 0.8.2 && < 0.9
      - test-framework-hunit >= 0.3.0.2 && < 0.4
      - test-framework-quickcheck2 >= 0.3.0.5 && < 0.4
      - HUnit >= 1.6
