hacker_targets = [
    "p01",
    "p02",
    "p03",
    "p04",
    "p05",
    "p06",
    "p07",
    "p08",
    "p09",
    "p10",
    "p11",
    "p12",
    "p13",
    "p14",
    "p15",
    "p16",
    "p17",
    "p18",
    "p19",
    "p20",
    "p21",
    "p22",
    "p23",
    "p24",
    "p25",
]
hacker_need_extra_targets = [
    "p07",
    "p08",
    "p09",
    "p11",
    "p12",
    "p13",
    "p16",
    "p19",
    "p20",
    "p21",
    "p22",
    "p23",
    "p24",
    "p25",
]
highway_targets = [
    "ZeroExtendResizeBitCast",
    "ConcatLowerLower",
    "ConcatUpperLower",
    "ConcatUpperUpper",
    "ZeroExtendResizeBitCast.Ext",
    "ConcatLowerUpper",
    "AddSub",
    "InsertLane",
    "OddEvenBlocks",
    "Lt128.Fixed",
    "MulEven",
    "MulOdd",
    "Min128.Fixed",
    "Lt128",
    "Min128",
]

vqsort_success_targets = [
    "PrevValue_Ascending_32",
    "PrevValue_Ascending_64",
    "PrevValue_Ascending_128",
    "SortPairsDistance4_Ascending_64",
    "SortPairsDistance1_Ascending_64",
    "SwapAdjacentPairs_32",
    "SwapAdjacentPairs_64",
    "SwapAdjacentQuads_32",
    "SortPairsDistance1_Ascending_32",
]
known_timeout_targets = [
    "p21",
    "Lt128",
    "Min128.Fixed",
    "Min128",
    "SwapAdjacentQuads_32",
    "SortPairsDistance1_Ascending_32"
]

vqsort_failed_targets = [
    "SortPairsDistance1_Ascending_failure_128",
    "SortPairsDistance4_Ascending_failure_32",
]